### ISSUE TITLE
Request: go.mod file

### ISSUE THREAD

**Issue by SolarLune** [tanema/gween#1]
Hello!

Thanks a lot for creating this tweening library! I'd like to ask if you could add a go.mod file to bring it up to date with modern Go packages, thereby making it possible to import without having to manually do so with `go get`.

**Comment by tanema** [comment]
Hey @SolarLune I have watched your game dev videos before! Anyways yeah I just added it thanks for opening the issue.

**Comment by SolarLune** [comment]
Hey, thanks a lot for watching my videos, haha! Also, thanks for adding the .mod file; appreciate it!
